In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv("final_data.csv")

In [3]:
data.head()

Unnamed: 0  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0           0   0            5.1           3.5            1.4           0.2   
1           1   1            4.7           3.2            1.6           0.2   
2           2   2            4.9           3.1            1.5           0.1   
3           3   3            4.4           2.9            1.4           0.2   
4           4   4            5.0           3.4            1.5           0.2   

       Species  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [4]:
data.drop(["Unnamed: 0", "Id"], axis=1, inplace=True )

In [5]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.7           3.2            1.6           0.2  Iris-setosa
2            4.9           3.1            1.5           0.1  Iris-setosa
3            4.4           2.9            1.4           0.2  Iris-setosa
4            5.0           3.4            1.5           0.2  Iris-setosa

## Label Encoding



In [6]:
le = LabelEncoder()

In [7]:
le.fit_transform(data["Species"])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
data["Species"] = le.fit_transform(data["Species"])

In [9]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.9           3.1            1.5           0.1        0
3            4.4           2.9            1.4           0.2        0
4            5.0           3.4            1.5           0.2        0

In [10]:
data.tail(20)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
134            5.8           2.7            5.1      1.900000        2
135            6.8           3.2            5.9      2.300000        2
136            6.7           3.3            5.7      2.500000        2
137            6.3           2.5            5.0      1.900000        2
138            6.3           2.7            4.9      1.800000        2
139            6.5           3.0            5.2      2.000000        2
140            6.2           3.4            5.4      2.300000        2
141            5.9           3.0            5.1      1.800000        2
142            6.4           2.8            5.6      2.200000        2
143            7.7           3.8            6.7      2.200000        2
144            5.8           2.8            5.1      1.180357        2
145            6.7           3.0            5.2      2.300000        2
146            7.7           3.0            6.1      2.300000        2
147            7.2           3.2            6.0      1.800000        2
148            6.3           2.8            5.1      1.500000        2
149            5.7           2.5            5.0      2.000000        2
150            6.8           3.0            5.5      2.100000        2
151            6.4           2.7            5.3      1.900000        2
152            7.2           3.6            6.1      2.500000        2
153            6.3           3.3            6.0      2.500000        2

## Veri Kontrolleri

In [11]:
data.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [12]:
data.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int64
dtype: object

## Train_test_split

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(data.iloc[:, :-1], data.iloc[:,-1], test_size=0.2)

In [15]:
x_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
46             5.3           3.7            1.5           0.2
63             6.6           3.0            4.4           1.4
92             5.5           2.4            3.7           1.0
71             6.6           2.9            4.6           1.3
81             5.5           2.5            4.0           1.3
..             ...           ...            ...           ...
127            6.5           3.2            5.1           2.0
128            6.7           3.3            5.7           2.1
12             4.3           3.0            1.1           0.1
20             5.1           3.8            1.5           0.3
36             5.1           3.4            1.5           0.2

[123 rows x 4 columns]

In [17]:
y_train.value_counts()

1    44
2    42
0    37
Name: Species, dtype: int64

In [18]:
y_test.value_counts()

2    12
0    10
1     9
Name: Species, dtype: int64

## Modelin Oluşturulması

In [19]:
import xgboost as xgb

In [20]:
xgb_cls = xgb.XGBClassifier(objective="multiclass:softmax", num_class=3)

In [21]:
xgb_cls.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=3,
              num_parallel_tree=None, ...)

In [28]:
preds = xgb_cls.predict(x_test)

In [29]:
preds

array([2, 0, 2, 0, 1, 2, 1, 2, 2, 0, 0, 2, 1, 2, 1, 2, 0, 0, 2, 0, 1, 1,
       1, 2, 0, 0, 1, 2, 1, 0, 2])

In [30]:
import numpy as np
np.array(y_test)

array([2, 0, 2, 0, 1, 2, 1, 2, 2, 0, 0, 2, 1, 2, 1, 2, 0, 0, 2, 0, 1, 1,
       1, 2, 0, 0, 1, 2, 1, 0, 2])

## Metrics

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [31]:
accuracy_score(y_test,preds)

1.0

In [32]:
confusion_matrix(y_test,preds)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 12]])